version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: webpack
    versions:
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
  - dependency-name: react-styleguidist
    versions:
    - 11.1.5
  - dependency-name: react
    versions:
    - 17.0.1
